version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: iot-spatial-interpolation 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_ROOT_PASSWORD: admin
    ports:
      - 3312:3306
    volumes:
      - ./db:/var/lib/postgresql

volumes:
  iot-spatial-interpolation:

