name: Build, Run & Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour.
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Make env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_UBIDOTS_KEY: ${{ secrets.UBIDOTS_KEY }}
    - name: Build python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'
    - run: sudo apt install grub-efi-amd64-bin
    - run: sudo apt-get update
    - run: sudo apt-get upgrade -y
    - run: sudo timedatectl set-timezone Australia/Sydney
    - run: sudo apt-get install build-essential libssl-dev libjpeg-dev libpng-dev libcurl4-openssl-dev curl wget git make sqlite3 libsqlite3-dev
    - run: sudo apt-get install software-properties-common
    - run: sudo apt install libgeos++-dev libgeos3.10.2 libgeos-c1v5 libgeos-dev libgeos-doc
    - name: Install Cmake
      run: sudo apt install -y cmake
    - name: Build PROJ
      run: sudo apt-get install proj-bin libproj-dev proj-data
    - run: pip install shapely --no-binary shapely 
    - run: pip install Cython
    - run: sudo update-ca-certificates
    - run: pip install git+https://github.com/SciTools/cartopy.git --no-binary cartopy
    - run: pip install -r requirements.txt && python main.py
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
