name: Build, Run & Deploy

on:
  schedule:
    - cron: "* 1 * * *" # Runs every hour
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'
    - run: sudo apt-get install proj-bin
    - run: sudo apt install libgeos++-dev libgeos-3.8.0 libgeos-c1v5 libgeos-dev libgeos-doc
    - run: pip install -r requirements.txt && python main.py
