name: Build, Run & Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Make env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_UBIDOTS_KEY: ${{ secrets.UBIDOTS_KEY }}
    - name: Build python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'
    - run: sudo apt-get update
    - run: sudo apt-get upgrade -y
    - run: sudo timedatectl set-timezone Australia/Sydney
    - run: sudo apt-get install build-essential libssl-dev libjpeg-dev libpng-dev libcurl4-openssl-dev curl wget git make
    - run: sudo apt install libgeos++-dev libgeos-3.8.0 libgeos-c1v5 libgeos-dev libgeos-doc
    - name: Install Cmake
      run: sudo apt install -y cmake
    - name: Build PROJ
      run: |
        cd /opt
        wget https://github.com/OSGeo/PROJ/releases/download/9.0.0/proj-9.0.0.tar.gz
        tar -xvzf proj-9.0.0.tar.gz
        rm proj-9.0.0.tar.gz
        cd proj-9.0.0
        mkdir build && cd build
        cmake ..
        cmake --build . --target install
    - run: pip install shapely --no-binary shapely
    - run: sudo update-ca-certificates
    - run: cd ~ && pip install -r requirements.txt && python main.py
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
